/**
 * Quickstart gate 6 — the link, before and after.
 *
 * Two halves. The first is the promise: every link minted before this feature
 * existed must decode to exactly what it decoded to then. `links-before.json`
 * was minted on the codec as it stood, by `links-before.mjs`, and is compared
 * against rather than regenerated — a corpus regenerated by the code it is
 * meant to hold to account is not a corpus.
 *
 * The second is the new grammar: `wf` and `wfd` round-trip byte-identically,
 * including a declaration carrying commas, spaces and the `·` the file's own
 * phrase uses, and each malformed class is refused whole with its reason.
 */
import { readFileSync } from 'node:fs';
import { decodeState, encodeState, LINK_VERSION } from '../../../src/permalink.js';
import { DEFAULT_PARAMETERS, DEFAULT_BYPASS } from '../../../src/controls.js';

let bad = 0;
const ok = (yes, label, detail = '') => {
  console.log(`${yes ? 'ok  ' : 'FAIL'}  ${label}${detail ? `  ${detail}` : ''}`);
  if (!yes) bad += 1;
};

/* ── the promise ──────────────────────────────────────────────────────── */

const before = JSON.parse(readFileSync(new URL('./links-before.json', import.meta.url), 'utf8'));

for (const desk of before.desks) {
  if (desk.hash === '') {
    ok(encodeState({ params: { ...DEFAULT_PARAMETERS }, bypass: { ...DEFAULT_BYPASS } }) === '',
      `"${desk.name}" still encodes to the empty fragment`);
    continue;
  }
  let now;
  try {
    const back = decodeState(desk.hash);
    now = { params: back.params, bypass: back.bypass, station: back.station, pin: back.pin ?? null };
  } catch (error) {
    ok(false, `"${desk.name}" still decodes`, error.message);
    continue;
  }
  ok(JSON.stringify(now) === JSON.stringify(desk.decoded), `"${desk.name}" decodes to what it always did`);
}

/**
 * A refusal whose wording this feature deliberately changed.
 *
 * The rule did not move and the link is refused exactly as it was; what changed
 * is that the sentence now names the second thing that could have supplied a
 * year. Saying "with no station to supply one" to a reader whose desk could
 * have had a weather file would send them to the one fix that was not
 * available to them.
 *
 * Declared rather than tolerated: an unexplained wording change in a refusal is
 * indistinguishable from a rule quietly moving, and this list is where the
 * difference is stated. Anything not in it has to match word for word.
 */
const REWORDED = new Map([
  [
    'v1&at=year.07-21T15',
    'the year pin now names the weather file as well as the station, since either supplies a year',
  ],
]);

for (const { raw, reason } of before.refusals) {
  let now = null;
  try {
    decodeState(raw);
  } catch (error) {
    now = error.message;
  }
  if (now === null) {
    ok(false, `"${raw}" is still refused`, 'it was accepted');
    continue;
  }
  if (now === reason) {
    ok(true, `"${raw}" is refused for the same reason`);
    continue;
  }
  const why = REWORDED.get(raw);
  ok(Boolean(why), `"${raw}" is still refused, reworded on purpose`, why ? `— ${why}` : `UNDECLARED: ${now}`);
}

ok(LINK_VERSION === 'v1', 'LINK_VERSION is still v1, because an added reserved key is the additive case');

/* ── the new grammar ──────────────────────────────────────────────────── */

const base = { params: { ...DEFAULT_PARAMETERS, width: 20 }, bypass: { ...DEFAULT_BYPASS } };
const file = {
  fingerprint: 'DT2jT6MRtUJ16oEg',
  declares: 'London Gatwick, ENG, GBR · CIBSE DSY1 2050s HIGH50 · WMO 037760',
};

const hash = encodeState({ ...base, file });
const back = decodeState(hash);
ok(back.file?.fingerprint === file.fingerprint, 'the fingerprint comes back');
ok(back.file?.declares === file.declares, 'the declaration comes back with its commas and its ·', back.file?.declares);
ok(back.station === null, 'a file link carries no station');
ok(encodeState({ ...base, file: back.file }) === hash, 're-encodes byte-identically');

const refusals = [
  ['wfd without wf', 'v1&wfd=London'],
  ['wf beside stn', 'v1&stn=725650&wf=DT2jT6MRtUJ16oEg'],
  ['a malformed wf', 'v1&wf=short'],
  ['wf given twice', 'v1&wf=DT2jT6MRtUJ16oEg&wf=DT2jT6MRtUJ16oEh'],
  ['a year pin with no climate at all', 'v1&at=year.7-21T15'],
];
for (const [label, raw] of refusals) {
  try {
    decodeState(raw);
    ok(false, `${label} is refused`);
  } catch (error) {
    ok(true, `${label} is refused`, error.message);
  }
}

// A year pin is about the run period, and a file supplies one exactly as a
// station does. Written the other way round, a link to a desk running an
// attached file and reading at one hour of it would be refused for the absence
// of a station it was never going to have.
try {
  const pinned = decodeState('v1&wf=DT2jT6MRtUJ16oEg&at=year.7-21T15');
  ok(pinned.pin?.month === 7 && pinned.pin?.hour === 15, 'a year pin rides on a file link');
} catch (error) {
  ok(false, 'a year pin rides on a file link', error.message);
}

// Both tokens at once is a caller bug, and the encoder says so rather than
// quietly preferring one.
try {
  encodeState({ ...base, file, station: { wmo: '725650', window: null } });
  ok(false, 'encoding a desk claiming two climates is refused');
} catch (error) {
  ok(true, 'encoding a desk claiming two climates is refused', error.message);
}

console.log(bad ? `\n${bad} failed` : '\nall passed');
process.exit(bad ? 1 : 0);
